### ISSUE TITLE
Got this weird error

### ISSUE THREAD

**Issue by FearedFusionX** [mathgames66/mathgames66.github.io#126]
There was like some sort of API Error that came up and idk what it is. It's not impacting gameplay as I've seen, however.

![Screenshot 2023-10-03 10 12 23 AM](https://github.com/mathgames66/mathgames66.github.io/assets/88568205/46a115fb-bbbb-4df2-9270-7f442107a98f)

**Comment by TheDiamondfinderNG** [comment]
Is the comment section there?

**Comment by TheDiamondfinderNG** [comment]
I can't work on the issue if you don't respond, man
