### ISSUE TITLE
How do you get these games?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [mathgames66/mathgames66.github.io#31]
I am trying to import Run 3 from coolmathgames on my website, but I don't know how to do it. Is it in an iframe? Should I copy every aspect of the code and put it all together? I need help pls

**Comment by 68r** [comment]
can you message me/friend request me on discord? (deleted#4522) ill give you instructions on how to do everything

**Comment by TheRealDigitalMaster** [comment]
Please email me at digitalmaster50000@gmail.com because my discord is blocked by my parents. I have a secret google account but you can email me there. I cannot say when I will read it, because my parents cannot be around to see me on my other account. I will try to see if I have enough time on my other acc to be on discord. I hope you understand :)
