### ISSUE TITLE
Adding sm64 is illegal

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [mathgames66/mathgames66.github.io#34]
Sorry, but I have to tell you before the police arrest you. Nintendo doesn't allow people to torrent their games, but even if people know how, it is best not to because it is their game and they will find out sooner or later. You have to pay money for a nintendo 64 game from Nintendo and not downloading or playing online for free unless it is by Nintendo. Please remove before I report.

**Comment by 68r** [comment]
No it is not, this emulation complies with the fair use doctrine because none of Nintendo's original game code is in it.

**Comment by THEBEST1278** [comment]
Dam bro abt to snitch lmao

**Comment by TheRealDigitalMaster** [comment]
they are going to find out anyway, just gonna make it sooner.
