### ISSUE TITLE
Forking issue

### ISSUE THREAD

**Issue by KrunchyKarrots** [mathgames66/mathgames66.github.io#71]
When I fork it, this happens. How can I fix this?
![Screenshot 2023-03-07 10 57 13 AM](https://user-images.githubusercontent.com/118313952/223523415-1587f67a-c55c-477a-b1e6-dffb4e63dd6e.png)

**Comment by 68r** [comment]
Weird, thats not supposed to occur. Sorry, but I have no choice but I'll have to come back to this on the next site update.

**Comment by KrunchyKarrots** [comment]
Ok, thanks.

**Comment by TheDiamondfinderNG** [comment]
What are you hosting this on? Are you hosting this on a local server or opening it as a file?

**Comment by KrunchyKarrots** [comment]
I'm hosting it on Github pages

**Comment by KrunchyKarrots** [comment]
Okay, thanks!

**Comment by TheDiamondfinderNG** [comment]
Alright, just update your page, and you should be good to go!

**Comment by KrunchyKarrots** [comment]
thanks!!
