### ISSUE TITLE
Game credit request/takedown

### ISSUE THREAD

**Issue by airtag8892** [mathgames66/mathgames66.github.io#72]
Hey! I'm airtag from discord.gg/3kh0. I am a moderator.

It appears you have taken https://mathgames66.github.io/p/paperio2.html from us. Please provide appropriate credit for the game or take it down.
If you would like to contact us, join discord.gg/3kh0 and reply with your username and tag or just reply to this issue.

Thank you.
![image](https://user-images.githubusercontent.com/120539605/223900644-599f9253-daa0-4d65-a38b-8e7fddae933f.png)

**Comment by Asleep123** [comment]
got it before me dang it

**Comment by 68r** [comment]
You/3kh0 team didnt create this game, so you dont have legal rights to take it down. Yes, scraping webgames at times can be difficult- but 3kh0 is open source, meaning that its absurd to police people using your code. Plus, it does not make sense when you scrape a game from someone else's site, but when I do just that, I am in the wrong. (I would not be surprised if it was without liscencing or if it was scraped from a closed-source site)

And I dont remove 'watermarks', so your website was being credited anyway.
